// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using DDN.SharedCode;

namespace System.ComponentModel.DataAnnotations
{

// these classes can be removed once EF 4.1 CodeFirst supports
// equivalent
public class UnicodeAttribute : Attribute
{
  public readonly bool IsUnicode;

  public UnicodeAttribute( ) : this(true) { }

  public UnicodeAttribute( bool isUnicode )
  {
    IsUnicode = isUnicode;
  }
}

public class DecimalPrecisionAttribute : Attribute
{
  public readonly byte Precision;
  public readonly byte Scale;

  public DecimalPrecisionAttribute( byte precision, byte scale )
  {
    Precision = precision;
    Scale = scale;
  }
}

}




	
	
	


